version: '3.8'

services:
    backend:
        image: extender777/nexus-backend:arm64
        ports:
            - '8004:3000'
        environment:
            - NODE_ENV=production
            - GOOGLE_KEY=${GOOGLE_KEY}
            - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
            - STABILITY_KEY=${STABILITY_KEY}
            - CLAUDE_KEY=${CLAUDE_KEY}
            - JWT_TOKEN=${JWT_TOKEN}
            - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
            - YAHOO_FINANCE_API_KEY=${YAHOO_FINANCE_API_KEY}
            - TELEGRAM_KEY=${TELEGRAM_KEY}
            - EMAIL=${EMAIL}
            - EMAIL_PASSWORD=${EMAIL_PASSWORD}
            - TOGETHER_KEY=${TOGETHER_KEY}
            - OPENAI_KEY=${OPENAI_KEY}
            - GEMINI_KEY=${GEMINI_KEY}
        restart: unless-stopped
        volumes:
            - ./nexus.json:/app/nexus.json
            - ./content:/app/content
        depends_on:
            - mongodb
            - python-shell

    mongodb:
        image: mongo:latest
        volumes:
            - mongo-data:/data/db
        restart: unless-stopped

    python-shell:
        image: python:3.12
        volumes:
            - ./python-scripts:/app
            - ./requirements.txt:/requirements.txt
        restart: unless-stopped
        working_dir: /app
        command:
            ['sh', '-c', 'pip install --no-cache-dir -r /requirements.txt && python -u shell.py']
        deploy:
            resources:
                limits:
                    cpus: '0.5'
                    memory: 512M
        environment:
            - PYTHONUNBUFFERED=1
            - PYTHON_SERVER_PORT=8000

volumes:
    mongo-data:
