name: CI/CD Pipeline

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch:

env:
    DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    IMAGE_NAME: nexus-backend
    SSH_HOST: ${{ secrets.SSH_HOST }}
    SSH_USER: ${{ secrets.SSH_USER }}
    SSH_KEY: ${{ secrets.SSH_KEY }}

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                  username: ${{ env.DOCKER_USERNAME }}
                  password: ${{ env.DOCKER_PASSWORD }}

            - name: Build and push
              uses: docker/build-push-action@v4
              with:
                  context: ./
                  push: true
                  tags: ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:arm64
                  platforms: linux/arm64

    deploy:
        needs: build-and-push
        runs-on: ubuntu-latest
        steps:
            - name: Deploy to SSH Host
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ env.SSH_HOST }}
                  username: ${{ env.SSH_USER }}
                  key: ${{ env.SSH_KEY }}
                  script: |
                      docker pull ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:arm64
                      docker-compose -f ~/nexus/docker-compose.yml down
                      docker-compose -f ~/nexus/docker-compose.yml up -d
